/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/announcements/': RouteRecordInfo<'/admin/announcements/', '/admin/announcements', Record<never, never>, Record<never, never>>,
    '/admin/announcements/[id]/edit': RouteRecordInfo<'/admin/announcements/[id]/edit', '/admin/announcements/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/announcements/new': RouteRecordInfo<'/admin/announcements/new', '/admin/announcements/new', Record<never, never>, Record<never, never>>,
    '/admin/directors/': RouteRecordInfo<'/admin/directors/', '/admin/directors', Record<never, never>, Record<never, never>>,
    '/admin/editor': RouteRecordInfo<'/admin/editor', '/admin/editor', Record<never, never>, Record<never, never>>,
    '/admin/forgot-password': RouteRecordInfo<'/admin/forgot-password', '/admin/forgot-password', Record<never, never>, Record<never, never>>,
    '/admin/history/': RouteRecordInfo<'/admin/history/', '/admin/history', Record<never, never>, Record<never, never>>,
    '/admin/login': RouteRecordInfo<'/admin/login', '/admin/login', Record<never, never>, Record<never, never>>,
    '/admin/new': RouteRecordInfo<'/admin/new', '/admin/new', Record<never, never>, Record<never, never>>,
    '/admin/organization/': RouteRecordInfo<'/admin/organization/', '/admin/organization', Record<never, never>, Record<never, never>>,
    '/admin/register': RouteRecordInfo<'/admin/register', '/admin/register', Record<never, never>, Record<never, never>>,
    '/admin/reset-password': RouteRecordInfo<'/admin/reset-password', '/admin/reset-password', Record<never, never>, Record<never, never>>,
    '/announcements': RouteRecordInfo<'/announcements', '/announcements', Record<never, never>, Record<never, never>>,
    '/directors': RouteRecordInfo<'/directors', '/directors', Record<never, never>, Record<never, never>>,
    '/history': RouteRecordInfo<'/history', '/history', Record<never, never>, Record<never, never>>,
    '/mock/announcements': RouteRecordInfo<'/mock/announcements', '/mock/announcements', Record<never, never>, Record<never, never>>,
    '/mock/directors': RouteRecordInfo<'/mock/directors', '/mock/directors', Record<never, never>, Record<never, never>>,
    '/mock/organization': RouteRecordInfo<'/mock/organization', '/mock/organization', Record<never, never>, Record<never, never>>,
    '/organization': RouteRecordInfo<'/organization', '/organization', Record<never, never>, Record<never, never>>,
    '/public-affairs': RouteRecordInfo<'/public-affairs', '/public-affairs', Record<never, never>, Record<never, never>>,
    '/testing': RouteRecordInfo<'/testing', '/testing', Record<never, never>, Record<never, never>>,
  }
}
